// Embeds the built game (game/dist/index.html) into the Expo app as a TS module.
// Run via `npm --prefix game run build:app`. The output is gitignored and regenerated
// on `npm start` in app/ and on EAS Build (eas-build-post-install).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const src = resolve(root, 'game/dist/index.html');
const out = resolve(root, 'app/src/game-html.generated.ts');

const html = readFileSync(src, 'utf8');
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out,
  '// AUTO-GENERATED by scripts/embed-game.mjs from game/dist/index.html. Do not edit.\n' +
  `export const GAME_HTML: string = ${JSON.stringify(html)};\n`);
console.log(`Embedded game: ${(html.length / 1024).toFixed(0)} KB -> app/src/game-html.generated.ts`);
